name: ambilrclone
on:
  workflow_dispatch:
jobs:
  ProsesBackup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Menginstall Rclone
      run: curl https://rclone.org/install.sh | sudo bash
    - name: Memuat konfigurasi Rclone
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.ftp }}
        EOF
    - name: Penyalinan
      run: |
        rclone copy "/.config/" "kuy:rclone"
